import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Pagination, Navigation } from 'swiper/modules';
import { Link } from 'react-router-dom';
import 'swiper/css'; import 'swiper/css/pagination'; import 'swiper/css/navigation';
import { contentData } from '../data/content';
import banner1 from '../assets/img/banner3.jpeg'; import banner2 from '../assets/img/banner2.jpg'; import banner3 from '../assets/img/banner.webp';
import Extra from './Extra'; import Coments from '../components/Coments';
import { getImageUrl } from '../utils/assets';

const content = contentData;
function Home() {
  return <main className="bg-gray-100 text-gray-900" id="home"><section><Swiper spaceBetween={30} centeredSlides autoplay={{ delay: 4000, disableOnInteraction: false }} pagination={{ clickable: true }} navigation modules={[Autoplay, Pagination, Navigation]} className="mySwiper">{[banner1, banner2, banner3].map((image, index) => <SwiperSlide key={index}><div className="h-[70vh] bg-cover bg-center relative" style={{ backgroundImage: `url(${image})` }}><div className="flex flex-col justify-center items-center text-center h-full text-white bg-black/50 px-4"><h1 className="text-5xl font-extrabold">ENEM STATION</h1><p className="mt-4 text-lg max-w-3xl font-semibold">O CEP (Copa do Ensino Público) é uma plataforma criada para organizar e centralizar conteúdos de reforço escolar para estudantes de escolas públicas.</p></div></div></SwiperSlide>)}</Swiper></section><section className="py-12" id="conteudo"><div className="max-w-7xl mx-auto px-4"><h2 className="text-center text-3xl font-bold mb-10">Conteúdo</h2><div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">{content.filter((item) => item.name && item['image-01']).map((item) => <div key={item.id} className="bg-white shadow rounded-lg overflow-hidden hover:shadow-lg transition"><Link to={`/season/${item.id}`} className="block text-gray-900"><img src={getImageUrl(item['image-01'])} alt={item.name} className="h-52 w-full object-cover transition-transform duration-300 hover:scale-105" /><div className="p-4"><h3 className="font-semibold text-lg">{item.name}</h3><p className="text-gray-500 text-sm mt-2">{item.description.length > 90 ? `${item.description.slice(0, 90)}...` : item.description}</p></div></Link></div>)}</div></div></section><section className="bg-gray-900 text-gray-200 py-12" id="sobre"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold mb-4">Sobre a CEP</h2><p className="text-gray-400 mb-4">O CEP (Copa do Ensino Público) é uma plataforma criada para organizar e centralizar conteúdos de reforço escolar, reunindo resumos, videoaulas, exercícios, explicações e anotações.</p><p className="text-gray-400">Nosso objetivo é aproximar os alunos do conhecimento.</p></div></section><Coments /><Extra /></main>;
}
export default Home;
